---
config:
  aws:
    profiles:
      - old-sandbox
      - sandbox
      - dev
    regions: [eu-north-1, ap-south-1, eu-west-3, eu-west-2, eu-west-1, ap-northeast-3, ap-northeast-2, ap-northeast-1, sa-east-1, ca-central-1, ap-southeast-1, ap-southeast-2, eu-central-1, us-east-1, us-east-2, us-west-1, us-west-2]
  elasticsearch:
    host: localhost
    port: 9200
    index: cc
  resources:
    # Select interesting resources to probe from
    #   https://cloudcustodian.io/docs/aws/resources/index.html
    # EC2
    # - "aws.ami"
    # - "aws.customer-gateway"
    - "aws.ebs"
    - "aws.ebs-snapshot"
    - "aws.ec2"
    - "aws.ec2-host"
    - "aws.ec2-reserved"
    # - "aws.ec2-spot-fleet-request"
    # - "aws.elastic-ip"
    # - "aws.eni"
    # - "aws.internet-gateway"
    # - "aws.key-pair"
    # - "aws.launch-template-version"
    # - "aws.nat-gateway"
    # - "aws.network-acl"
    # - "aws.peering-connection"
    # - "aws.route-table"
    # - "aws.security-group"
    # - "aws.subnet"
    # - "aws.transit-attachment"
    # - "aws.transit-gateway"
    - "aws.vpc"
    # - "aws.vpc-endpoint"
    # - "aws.vpn-connection"
    # - "aws.vpn-gateway"

    # ECS
    - "aws.ecs"
    - "aws.ecs-container-instance"
    - "aws.ecs-service"
    - "aws.ecs-task"
    - "aws.ecs-task-definition"
    # EKS
    - "aws.eks"
    - "aws.eks-nodegroup"
    # S3
    - "aws.s3"
    # GLUE
    # - "aws.glue-catalog"
    # - "aws.glue-classifier"
    # - "aws.glue-connection"
    - "aws.glue-crawler"
    - "aws.glue-database"
    - "aws.glue-dev-endpoint"
    - "aws.glue-job"
    # - "aws.glue-ml-transform"
    # - "aws.glue-security-configuration"
    - "aws.glue-table"
    - "aws.glue-trigger"
    - "aws.glue-workflow"
